version: '3.8'

services:
  # Бэкенд на Python
  backend:
    build: ./backend
    container_name: hackathon_backend
    ports:
      - "8000:8000"
    volumes:
      # Чтобы модель подгружалась корректно
      - ./backend:/app
    restart: always

  # Фронтенд на React + Nginx
  frontend:
    build: ./frontend
    container_name: hackathon_frontend
    ports:
      - "3000:80" # Фронт будет доступен на порту 3000
    depends_on:
      - backend
    restart: always